### ISSUE TITLE
코드 올려주셔서 감사합니다~

### ISSUE THREAD

**Issue by ghdtnsld** [skatn/hangul_clock#2]
코드 올려주셔서 감사합니다~
덕분에 잘 만들었어요~
오전 오후 나타내는게 표시 되었다가 사라지는게 좀 아쉬워서 그러는데
오전 오후를 2초 간격의 숨쉬기모드로 코드 작성 가능하나요?
![KakaoTalk_20200529_113516002](https://user-images.githubusercontent.com/64360941/83214878-9da69200-a1a0-11ea-8206-b89d0104d7b6.jpg)

**Comment by ghost** [comment]
189번라인 보시면
if((nowTime.second() < 5) || ((config == SET_HOUR) || (config == SET_MINUTE))){
해당 코드를 아래 코드로 변경하면 될거같네요!

if(((nowTime.second()+1)%4 < 2) || ((config == SET_HOUR) || (config == SET_MINUTE))){

**Comment by ghost** [comment]
혹시 가능하시다면 서로 사진과 회로도 공유 가능할까요?

오픈채팅 링크입니다 ㅎㅎ
https://open.kakao.com/o/gyCGG6dc
